version: '3'

services:

    maks:
        build: .
        container_name: laravel-maks
        entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
        environment:
            - _DB_HOST=db
            - _DB_DATABASE=laravel_maks
            - _DB_USERNAME=root
            - _DB_PASSWORD=root
        volumes:
            - .:/var/www
        networks:
            - app-maks-network
        depends_on:
            - db
            - redis

    nginx:
        build: .docker/nginx
        container_name: laravel-nginx-maks
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-maks-network
        depends_on:
            - maks

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: laravel-maks-db
        restart: always
        tty: true
        ports:
            - "33007:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=laravel_maks
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks:
            - app-maks-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel-phpmyadmin
        links:
            - db
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
        networks:
            - app-maks-network

    redis:
        image: redis:alpine
        container_name: laravel-maks-redis
        expose:
            - 6379
        networks:
            - app-maks-network

networks:
    app-maks-network:
        driver: bridge