<?php

/**
 * Created by Claudio Campos.
 * User: callcocam@gmail.com
 * https://www.sigasmart.com.br
 */

namespace App\Http\Controllers;

use App\Forms\OrderGridForm;
use App\GridOrderItem;
use App\Http\Requests\OrderGridStore;
use App\OrderGrid;

class OrderGridController extends AbstractController
{
    protected $template = 'orders';

    protected $routeStore = 'orders-grids';

    protected $model = OrderGrid::class;

    protected $formClass = OrderGridForm::class;
    /**
     * Store a newly created resource in storage.
     *
     * @param OrderGridStore $request
     * @return \Illuminate\Http\Response
     */
    public function store(OrderGridStore $request)
    {
        $this->template = "edit-grids";

        return $this->save($request);
    }

    public function edit($id)
    {
        $this->templateEdit = "edit-grids";

        return parent::edit($id); // TODO: Change the autogenerated stub
    }

    public function deleteItemGrid($id)
    {
        $this->model = GridOrderItem::class;

        $model = $this->getModel()->findById($id);

        if (!$model) {

            notify()->error("O modelo não foi informado, se o problema persistir contate o administardor!!!!");

            return back()->withErrors("O modelo não foi informado, se o problema persistir contate o administardor!!!!");
        }

        if ($this->getModel()->deleteBy($model)) {

            notify()->success($this->getModel()->getMessage());

            return back()->with('success', $this->getModel()->getMessage());
        }

        notify()->error($this->getModel()->getMessage());

        return back()->withErrors($this->getModel()->getMessage());
    }
}
